lane :build_appstore do
  xcversion(version: "11.5")

  gym(
    scheme: "CapOMat",
    configuration: "Release",
    output_directory: "./build/app-store",
    clean: true,
    export_options: "./config/AppStoreConfiguration.plist",
    output_name: "Cap-o-Mat.ipa"
  )

end

lane :test do
  xcversion(version: "11.5")

  run_tests(scheme: "CapOMat")

end

lane :upload_binary do
  upload_to_testflight(
    username: "lfranco@greenwave-solutions.com",
    ipa: "./build/app-store/Cap-o-Mat.ipa",
    team_id: "159005"
  )
end

lane :upload_metadata do
  deliver(
    app_identifier: "com.app-o-mat.CapOMat",
    username: "lfranco@greenwave-solutions.com",
    team_id: "159005",
    force: true,
    skip_screenshots: true,
    skip_binary_upload: true,
    metadata_path: "./deliver/metadata"
  )
end

lane :upload_screenshots do
  deliver(
    app_identifier: "com.app-o-mat.CapOMat",
    username: "lfranco@greenwave-solutions.com",
    team_id: "159005",
    force: true,
    skip_screenshots: false,
    skip_metadata: true,
    skip_binary_upload: true,
    screenshots_path: "./deliver/screenshots"
  )
end